### ISSUE TITLE
lzr runtime fatal error

### ISSUE THREAD

**Issue by wangtz19** [stanford-esrg/lzr#10] opened 2022-08-27 09:15 UTC
I'm running lzr following instructions in README.md, when I ran
```
 sudo zmap --target-port=9002 --output-filter="success = 1 && repeat = 0" \
-f "saddr,daddr,sport,dport,seqnum,acknum,window" -O json --source-ip=172.26.48.1 -n 20 | \
sudo ./lzr --handshakes http,tls
```
I encountered the followed error
```
++Writing results to file: default_20220827165939.json
++Handshakes: http,tls
++Worker threads: 1
++Timeout Interval (s): 5
++Retransmit Interval (s): 1
++Number of Retransmitions: 1
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x8297b5, 0x16)
        /usr/lib/go-1.13/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc004000000, 0x538000000, 0x10a1638)
        /usr/lib/go-1.13/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0xb59f20, 0x53724e000, 0x459140, 0x7ff928219008)
        /usr/lib/go-1.13/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0xb59f20, 0x29b927, 0xffffffff)
        /usr/lib/go-1.13/src/runtime/mheap.go:1255 +0xa3
runtime.(*mheap).allocSpanLocked(0xb59f20, 0x29b927, 0x10a1648, 0x421035)
        /usr/lib/go-1.13/src/runtime/mheap.go:1170 +0x266
runtime.(*mheap).alloc_m(0xb59f20, 0x29b927, 0x7ff924790100, 0x7ff92479a9f0)
        /usr/lib/go-1.13/src/runtime/mheap.go:1022 +0xc2
runtime.(*mheap).alloc.func1()
        /usr/lib/go-1.13/src/runtime/mheap.go:1093 +0x4c
runtime.(*mheap).alloc(0xb59f20, 0x29b927, 0x7ff924010100, 0x1)
        /usr/lib/go-1.13/src/runtime/mheap.go:1092 +0x8a
runtime.largeAlloc(0x53724e000, 0x1, 0xc00015bb18)
        /usr/lib/go-1.13/src/runtime/malloc.go:1138 +0x97
runtime.mallocgc.func1()
        /usr/lib/go-1.13/src/runtime/malloc.go:1033 +0x46
runtime.systemstack(0x45c6e4)
        /usr/lib/go-1.13/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /usr/lib/go-1.13/src/runtime/proc.go:1146

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/lib/go-1.13/src/runtime/asm_amd64.s:330 fp=0xc00015bd20 sp=0xc00015bd18 pc=0x45c7e0
runtime.mallocgc(0x53724e000, 0x80c660, 0x1, 0xc0001e76c4)
        /usr/lib/go-1.13/src/runtime/malloc.go:1032 +0x895 fp=0xc00015bdc0 sp=0xc00015bd20 pc=0x40fb75
runtime.makechan(0x7753a0, 0x5f5e100, 0xc0000b8060)
        /usr/lib/go-1.13/src/runtime/chan.go:106 +0x153 fp=0xc00015be08 sp=0xc00015bdc0 pc=0x4083b3
github.com/stanford-esrg/lzr.ConstructWritingQueue(...)
        /home/wangtz/lzr/construct_main_routines.go:49
github.com/stanford-esrg/lzr/bin.LZRMain()
        /home/wangtz/lzr/bin/bin.go:43 +0x174 fp=0xc00015bf50 sp=0xc00015be08 pc=0x5d5aa4
main.main()
        /home/wangtz/lzr/cmd/lzr/main.go:11 +0x20 fp=0xc00015bf60 sp=0xc00015bf50 pc=0x738450
runtime.main()
        /usr/lib/go-1.13/src/runtime/proc.go:203 +0x21e fp=0xc00015bfe0 sp=0xc00015bf60 pc=0x4332ae
runtime.goexit()
        /usr/lib/go-1.13/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00015bfe8 sp=0xc00015bfe0 pc=0x45e8b1
```
it seems that my machine's memory has run out, how should deal with this problem?

**Comment by LizIzhikevich** [comment] 2022-08-28 18:28
Depending upon the amount of RAM your machine has, it is possible that you are running out of memory due to the following:
zmap is scanning very fast -> a lot of SYN-ACK responses / second -> LZR needs to keep track of a lot connections at once -> LZR state table uses up all of your machines memory.

Either slowing down the scanning rate of zmap, or using ztee (https://github.com/zmap/zmap/blob/main/src/ztee.1.ronn) to help buffer some of the SYN-ACKs coming from zmap, should help.

**Comment by wangtz19** [comment] 2022-08-29 09:57
> Depending upon the amount of RAM your machine has, it is possible that you are running out of memory due to the following: zmap is scanning very fast -> a lot of SYN-ACK responses / second -> LZR needs to keep track of a lot connections at once -> LZR state table uses up all of your machines memory.
> 
> Either slowing down the scanning rate of zmap, or using ztee (https://github.com/zmap/zmap/blob/main/src/ztee.1.ronn) to help buffer some of the SYN-ACKs coming from zmap, should help.

I have tried both methods, but the same error still exists.
Even if I simply ran `./lzr`, what I got was the same above error information.
I don't think it's because of RAM shortage, maybe there are some problems with my runtime environment or something else.

**Comment by LizIzhikevich** [comment] 2022-08-29 13:00
How much RAM/disk space does lzr have access to on your machine?

Yea you should be able to verify if running out of RAM is the problem by running htop at the same time as running lzr and then monitoring the RAM. I cannot personally reproduce your problem on my machine, so its hard for me to help.

**Comment by wangtz19** [comment] 2022-08-30 04:38
```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:          15747         765       10076         124        4905       14682
Swap:             0           0           0
```
The total RAM on my machine is 15747M, lzr crashs down (out of memory) immediately when I start running it, so I cannot monitor its RAM usage by tools like htop.

**Comment by wangtz19** [comment] 2022-08-30 14:21
I reset git version to commit on 28 August, 2021, now the above problem disappears.

**Comment by wangtz19** [comment] 2022-08-30 16:14
Sorry to bother you again, here comes another problem. Now I want to complete full L7 handshake, i.e. ran
```
sudo zmap --target-port=9002 --output-filter="success = 1 && repeat = 0" \
-f "saddr,daddr,sport,dport,seqnum,acknum,window" -O json --source-ip=$source-ip | \
sudo ./lzr --handshakes wait,http,tls -feedZGrab | \
zgrab multiple -c etc/all.ini 
```
the error was
```
FATA[0000] could not parse multiple: etc/all.ini:6: strconv.ParseUint: parsing "x": invalid syntax
```
I checked `etc/all.ini` and found all ports in `etc/all.ini` were given the same value `x`
```
[smtp]
name="smtps"
trigger="smtps"
port=x
smtps=True

[http]
name="http"
trigger="http"
port=x

[snmp]
name="snmp"
trigger="snmp"
port=x
``` 
Do I have to change them to proper values one  by one ?

**Comment by LizIzhikevich** [comment] 2022-08-30 16:34
yes, I have updated the instructions to reflect that. 
I am also closing this issue since you have resolved your fatal error.

**Closed by LizIzhikevich** 2022-08-30 16:34 UTC
